# ===================================
#  List Behavior Config
# ===================================

title: Deine Coupons
list:
    columns:
        code:
            label: Code
        uses:
            label: Benutzt
            type: number
        last_used_at:
            label: Zuletzt benutzt
            type: timetense

modelClass: Bbf\Models\Coupon
recordUrl: affiliates/coupons/view/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showSetup: true
# showCheckboxes: true
