# ===================================
#  List Behavior Config
# ===================================

title: Deine Coupons
list: ~/modules/bbf/models/coupon/columns.yaml
modelClass: Bbf\Models\Coupon
recordUrl: affiliates/coupons/view/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showSetup: true
# showCheckboxes: true
